# Generated by Django 5.2.13 on 2026-04-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_smartbin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartbin',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='bin_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='bin_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='collection_schedule',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartbin',
            name='status',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='smartbin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='MaintenanceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('full', 'Bin Full'), ('jammed', 'Bin Jammed'), ('damaged', 'Bin Damaged')], max_length=50)),
                ('message', models.TextField(blank=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.smartbin')),
            ],
        ),
    ]
