# Generated by Django 6.0.4 on 2026-04-12 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_smartbin_address_smartbin_bin_id_smartbin_bin_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('reward_points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('smart_bin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.smartbin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
