# Generated by Django 6.0.4 on 2026-04-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_depositlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositlog',
            name='material',
            field=models.CharField(choices=[('Polyethylene', 'Polyethylene'), ('Polypropylene', 'Polypropylene'), ('Plastic', 'Plastic'), ('Mixed Plastic', 'Mixed Plastic')], default='Polyethylene', max_length=100),
        ),
    ]
