# Generated by Django 6.0.4 on 2026-04-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_userprofile'),
        ('core', '0005_alter_depositlog_material'),
    ]

    operations = [
    ]
